// nextjs/app/page.tsx
"use client";
import { litSetup } from 'lit-client-setup';

export default function Home() {


    return (
        <div className="flex flex-col items-center gap-[1.2rem]">
            <h1>Lit with Next</h1>
            <p>Check console</p>
            <button
                onClick={litSetup}
                className="bg-gray-700 text-white font-bold py-2 px-4 rounded hover:bg-gray-600 focus:outline-none focus:shadow-outline"
            >
                Instantiate Lit
            </button>
        </div>
    );
}

// vuejs/src/App.vue
<template>
  <div class="App">
    <h1>Lit with Vue</h1>
    <p>Check console</p>
    <button @click="instantiateLit">Instantiate Lit</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { litSetup } from 'lit-client-setup';

export default defineComponent({
  name: 'App',
  methods: {
    async instantiateLit() {
      await litSetup();
    }
  }
});
</script>

<style scoped>
.App {
  text-align: center;
}

button {
  margin-top: 20px;
  padding: 10px 20px;
  font-size: 16px;
}
</style>
